clean_rollout_path = true
max_batch_size = 96

[monitor.wandb]
project = "bartolds-math-multinode"

[model]
name = "Qwen/Qwen2.5-1.5B-Instruct"
max_model_len = 1024

[data]
name = "nlile/hendrycks-MATH-benchmark"

[parallel]
dp = 6

[rl]
ckpt_path = "/p/vast1/bartolds/checkpoints"
clean_ckpt_path = true

# Custom rollout path
rollout_path = "/p/vast1/bartolds/rollouts"