max_steps = 351 #251
clean_rollout_path = true
rollout_path = "/p/vast1/bartolds/tba-prime/TBA_qwen_async5_rollouts"
#max_batch_size = "auto"
#max_batch_size = 800
#max_batch_size = 512
#max_batch_size = 256 # for neurips
#max_batch_size = 384 # was 256 for first run
max_batch_size = 128 

[monitor.wandb]
project = "math-debug"
name = "TBA_infer_qwen_async5_3072_b0001_k64"

[model]
#name = "Qwen/Qwen2.5-1.5B-Instruct"
#name = "Qwen/Qwen3-8B"
#name = "Qwen/Qwen2.5-7B-Instruct"
name = "Qwen/Qwen2.5-7B"

#max_model_len = 2048
max_model_len = 3072

[data]
name = "/p/vast1/bartolds/math-hendrycks-genesys-format/data/train_set"

[parallel]
dp = 4

[sampling]
n = 64

[rl]
async_level = 5 # was default, 2
ckpt_path = "/p/vast1/bartolds/tba-prime/TBA_qwen_async5_checkpoints"
clean_ckpt_path = true
